version: "3.7"
services:
  workspace:
    image: enlibe/node-sdk:0.1.0
    environment:
      - NPM_TOKEN
    entrypoint: []
    command: ["bash"]
    user: "0" #root
    networks:
      - host
    volumes:
      - type: volume
        source: npm_cache
        target: /var/cache/npm
      - type: bind
        source: .
        target: /workspace
    working_dir: /workspace
networks:
  host:
    external: true
volumes:
  npm_cache:
    driver: local
    name: global_npm_cache
