name: npmjs.com/package/@enlibe/locales
on:
  push:
    branches:
      - master
    paths:
      - "**"
      - "!**.md"
jobs:
  CI:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: development
      NPM_TOKEN: "${{ secrets.NPM_TOKEN }}"
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run format:check
      - run: npm run build
      - run: npm run test
#      - run: npm publish
